# Dynamic libraries
if(TARGET_PLATFORM_WINDOWS)
	if (NOT CMAKE_BUILD_TYPE)
		set(RELEASE_CONFIGURATIONS ${CMAKE_CONFIGURATION_TYPES})
		list(REMOVE_ITEM RELEASE_CONFIGURATIONS ${DEBUG_CONFIGURATIONS})
		foreach (config IN ITEMS ${DEBUG_CONFIGURATIONS})
			file(COPY "${BIN_DEBUG}/" DESTINATION "${CMAKE_RUNTIME_OUTPUT_DIRECTORY}/${config}/")
		endforeach()
		foreach (config IN ITEMS ${RELEASE_CONFIGURATIONS})
			file(COPY "${BIN_RELEASE}/" DESTINATION "${CMAKE_RUNTIME_OUTPUT_DIRECTORY}/${config}/")
		endforeach()
	else()
		list(FIND ${DEBUG_CONFIGURATIONS} ${CMAKE_BUILD_TYPE} is_debug)
		message(${DEBUG_CONFIGURATIONS})
		message(${is_debug})
		if (${is_debug} EQUAL -1)
			set(src_dir ${BIN_RELEASE})
		else()
			set(src_dir ${BIN_DEBUG})
		endif()
		file(COPY "${src_dir}/" DESTINATION "${CMAKE_RUNTIME_OUTPUT_DIRECTORY}/")
	endif()
endif()